# Nome da Aplicação
spring.application.name=aesthetix

# Banco de Dados MySQL no Docker
spring.datasource.url=jdbc:mysql://localhost:3306/aesthetix_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=aesthetix
spring.datasource.password=aesthetix_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuração da Porta da API
server.port=8081