# Nome da Aplicação
spring.application.name=aesthetix
# Banco de Dados MySQL no Docker
spring.datasource.url=jdbc:mysql://localhost:3306/aesthetix_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=aesthetix
spring.datasource.password=aesthetix_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Porta da API
server.port=8081

# JWT
jwt.secret=ChangeThisSecretKeyToAStrongOneOfAtLeast32Bytes!
jwt.expiration-ms=3600000

# Springdoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs